package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1



/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer idBrand;
     private String name;

    public Brand() {
    }

    public Brand(String name) {
       this.name = name;
    }
   
    public Integer getIdBrand() {
        return this.idBrand;
    }
    
    public void setIdBrand(Integer idBrand) {
        this.idBrand = idBrand;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


