package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idCart;
     private Product product;
     private Double qty;
     private Double totPrice;

    public Cart() {
    }

	
    public Cart(Product product) {
        this.product = product;
    }
    public Cart(Product product, Double qty, Double totPrice) {
       this.product = product;
       this.qty = qty;
       this.totPrice = totPrice;
    }
   
    public Integer getIdCart() {
        return this.idCart;
    }
    
    public void setIdCart(Integer idCart) {
        this.idCart = idCart;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getTotPrice() {
        return this.totPrice;
    }
    
    public void setTotPrice(Double totPrice) {
        this.totPrice = totPrice;
    }




}


