package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private Integer idCheckout;
     private CardDetails cardDetails;
     private PaymentMethod paymentMethod;
     private ShippingAddress shippingAddress;
     private ShippingCost shippingCost;
     private User user;
     private Date purchasedDate;
     private String deliveryStatus;
     private String paidStatus;
     private Double subTotal;
     private Double myCost;
     private Set checkoutHasProducts = new HashSet(0);

    public Checkout() {
    }

	
    public Checkout(CardDetails cardDetails, PaymentMethod paymentMethod, ShippingAddress shippingAddress, ShippingCost shippingCost, User user) {
        this.cardDetails = cardDetails;
        this.paymentMethod = paymentMethod;
        this.shippingAddress = shippingAddress;
        this.shippingCost = shippingCost;
        this.user = user;
    }
    public Checkout(CardDetails cardDetails, PaymentMethod paymentMethod, ShippingAddress shippingAddress, ShippingCost shippingCost, User user, Date purchasedDate, String deliveryStatus, String paidStatus, Double subTotal, Double myCost, Set checkoutHasProducts) {
       this.cardDetails = cardDetails;
       this.paymentMethod = paymentMethod;
       this.shippingAddress = shippingAddress;
       this.shippingCost = shippingCost;
       this.user = user;
       this.purchasedDate = purchasedDate;
       this.deliveryStatus = deliveryStatus;
       this.paidStatus = paidStatus;
       this.subTotal = subTotal;
       this.myCost = myCost;
       this.checkoutHasProducts = checkoutHasProducts;
    }
   
    public Integer getIdCheckout() {
        return this.idCheckout;
    }
    
    public void setIdCheckout(Integer idCheckout) {
        this.idCheckout = idCheckout;
    }
    public CardDetails getCardDetails() {
        return this.cardDetails;
    }
    
    public void setCardDetails(CardDetails cardDetails) {
        this.cardDetails = cardDetails;
    }
    public PaymentMethod getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public ShippingAddress getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void setShippingAddress(ShippingAddress shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    public ShippingCost getShippingCost() {
        return this.shippingCost;
    }
    
    public void setShippingCost(ShippingCost shippingCost) {
        this.shippingCost = shippingCost;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getPurchasedDate() {
        return this.purchasedDate;
    }
    
    public void setPurchasedDate(Date purchasedDate) {
        this.purchasedDate = purchasedDate;
    }
    public String getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public String getPaidStatus() {
        return this.paidStatus;
    }
    
    public void setPaidStatus(String paidStatus) {
        this.paidStatus = paidStatus;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Double getMyCost() {
        return this.myCost;
    }
    
    public void setMyCost(Double myCost) {
        this.myCost = myCost;
    }
    public Set getCheckoutHasProducts() {
        return this.checkoutHasProducts;
    }
    
    public void setCheckoutHasProducts(Set checkoutHasProducts) {
        this.checkoutHasProducts = checkoutHasProducts;
    }




}


