package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1



/**
 * CheckoutHasProduct generated by hbm2java
 */
public class CheckoutHasProduct  implements java.io.Serializable {


     private Integer chpid;
     private Checkout checkout;
     private Product product;
     private Double qty;

    public CheckoutHasProduct() {
    }

	
    public CheckoutHasProduct(Checkout checkout, Product product) {
        this.checkout = checkout;
        this.product = product;
    }
    public CheckoutHasProduct(Checkout checkout, Product product, Double qty) {
       this.checkout = checkout;
       this.product = product;
       this.qty = qty;
    }
   
    public Integer getChpid() {
        return this.chpid;
    }
    
    public void setChpid(Integer chpid) {
        this.chpid = chpid;
    }
    public Checkout getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Checkout checkout) {
        this.checkout = checkout;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }




}


