package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer idGrn;
     private Product product;
     private Double buyPrice;
     private Double selPrice;
     private Double qty;
     private Date addedDate;

    public Grn() {
    }

	
    public Grn(Product product) {
        this.product = product;
    }
    public Grn(Product product, Double buyPrice, Double selPrice, Double qty, Date addedDate) {
       this.product = product;
       this.buyPrice = buyPrice;
       this.selPrice = selPrice;
       this.qty = qty;
       this.addedDate = addedDate;
    }
   
    public Integer getIdGrn() {
        return this.idGrn;
    }
    
    public void setIdGrn(Integer idGrn) {
        this.idGrn = idGrn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getBuyPrice() {
        return this.buyPrice;
    }
    
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }
    public Double getSelPrice() {
        return this.selPrice;
    }
    
    public void setSelPrice(Double selPrice) {
        this.selPrice = selPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }




}


