package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod  implements java.io.Serializable {


     private Integer idPaymentMethod;
     private String method;
     private Set checkouts = new HashSet(0);

    public PaymentMethod() {
    }

    public PaymentMethod(String method, Set checkouts) {
       this.method = method;
       this.checkouts = checkouts;
    }
   
    public Integer getIdPaymentMethod() {
        return this.idPaymentMethod;
    }
    
    public void setIdPaymentMethod(Integer idPaymentMethod) {
        this.idPaymentMethod = idPaymentMethod;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }




}


