package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private Category category;
     private String productCode;
     private String name;
     private String movement;
     private String display;
     private String style;
     private String features;
     private String caseMaterial;
     private String caseDiameter;
     private String caseThickness;
     private String bandMaterial;
     private String bandLength;
     private String bandWidth;
     private Set carts = new HashSet(0);
     private Set productImages = new HashSet(0);
     private Set checkoutHasProducts = new HashSet(0);
     private Set grns = new HashSet(0);
     private Set stocks = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category) {
        this.category = category;
    }
    public Product(Category category, String productCode, String name, String movement, String display, String style, String features, String caseMaterial, String caseDiameter, String caseThickness, String bandMaterial, String bandLength, String bandWidth, Set carts, Set productImages, Set checkoutHasProducts, Set grns, Set stocks) {
       this.category = category;
       this.productCode = productCode;
       this.name = name;
       this.movement = movement;
       this.display = display;
       this.style = style;
       this.features = features;
       this.caseMaterial = caseMaterial;
       this.caseDiameter = caseDiameter;
       this.caseThickness = caseThickness;
       this.bandMaterial = bandMaterial;
       this.bandLength = bandLength;
       this.bandWidth = bandWidth;
       this.carts = carts;
       this.productImages = productImages;
       this.checkoutHasProducts = checkoutHasProducts;
       this.grns = grns;
       this.stocks = stocks;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMovement() {
        return this.movement;
    }
    
    public void setMovement(String movement) {
        this.movement = movement;
    }
    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }
    public String getCaseMaterial() {
        return this.caseMaterial;
    }
    
    public void setCaseMaterial(String caseMaterial) {
        this.caseMaterial = caseMaterial;
    }
    public String getCaseDiameter() {
        return this.caseDiameter;
    }
    
    public void setCaseDiameter(String caseDiameter) {
        this.caseDiameter = caseDiameter;
    }
    public String getCaseThickness() {
        return this.caseThickness;
    }
    
    public void setCaseThickness(String caseThickness) {
        this.caseThickness = caseThickness;
    }
    public String getBandMaterial() {
        return this.bandMaterial;
    }
    
    public void setBandMaterial(String bandMaterial) {
        this.bandMaterial = bandMaterial;
    }
    public String getBandLength() {
        return this.bandLength;
    }
    
    public void setBandLength(String bandLength) {
        this.bandLength = bandLength;
    }
    public String getBandWidth() {
        return this.bandWidth;
    }
    
    public void setBandWidth(String bandWidth) {
        this.bandWidth = bandWidth;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getProductImages() {
        return this.productImages;
    }
    
    public void setProductImages(Set productImages) {
        this.productImages = productImages;
    }
    public Set getCheckoutHasProducts() {
        return this.checkoutHasProducts;
    }
    
    public void setCheckoutHasProducts(Set checkoutHasProducts) {
        this.checkoutHasProducts = checkoutHasProducts;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


