package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {


     private Integer idProductImage;
     private Product product;
     private String imageOne;
     private String imageTwo;
     private String imageThree;

    public ProductImage() {
    }

	
    public ProductImage(Product product) {
        this.product = product;
    }
    public ProductImage(Product product, String imageOne, String imageTwo, String imageThree) {
       this.product = product;
       this.imageOne = imageOne;
       this.imageTwo = imageTwo;
       this.imageThree = imageThree;
    }
   
    public Integer getIdProductImage() {
        return this.idProductImage;
    }
    
    public void setIdProductImage(Integer idProductImage) {
        this.idProductImage = idProductImage;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getImageOne() {
        return this.imageOne;
    }
    
    public void setImageOne(String imageOne) {
        this.imageOne = imageOne;
    }
    public String getImageTwo() {
        return this.imageTwo;
    }
    
    public void setImageTwo(String imageTwo) {
        this.imageTwo = imageTwo;
    }
    public String getImageThree() {
        return this.imageThree;
    }
    
    public void setImageThree(String imageThree) {
        this.imageThree = imageThree;
    }




}


