package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ShippingCost generated by hbm2java
 */
public class ShippingCost  implements java.io.Serializable {


     private Integer idShippingCost;
     private HomeTown homeTown;
     private Double cost;
     private Set checkouts = new HashSet(0);

    public ShippingCost() {
    }

	
    public ShippingCost(HomeTown homeTown) {
        this.homeTown = homeTown;
    }
    public ShippingCost(HomeTown homeTown, Double cost, Set checkouts) {
       this.homeTown = homeTown;
       this.cost = cost;
       this.checkouts = checkouts;
    }
   
    public Integer getIdShippingCost() {
        return this.idShippingCost;
    }
    
    public void setIdShippingCost(Integer idShippingCost) {
        this.idShippingCost = idShippingCost;
    }
    public HomeTown getHomeTown() {
        return this.homeTown;
    }
    
    public void setHomeTown(HomeTown homeTown) {
        this.homeTown = homeTown;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }




}


