package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ShippingAddress generated by hbm2java
 */
public class ShippingAddress  implements java.io.Serializable {


     private Integer idShippingAddress;
     private HomeTown homeTown;
     private User user;
     private String address;
     private Set checkouts = new HashSet(0);

    public ShippingAddress() {
    }

	
    public ShippingAddress(HomeTown homeTown, User user) {
        this.homeTown = homeTown;
        this.user = user;
    }
    public ShippingAddress(HomeTown homeTown, User user, String address, Set checkouts) {
       this.homeTown = homeTown;
       this.user = user;
       this.address = address;
       this.checkouts = checkouts;
    }
   
    public Integer getIdShippingAddress() {
        return this.idShippingAddress;
    }
    
    public void setIdShippingAddress(Integer idShippingAddress) {
        this.idShippingAddress = idShippingAddress;
    }
    public HomeTown getHomeTown() {
        return this.homeTown;
    }
    
    public void setHomeTown(HomeTown homeTown) {
        this.homeTown = homeTown;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }




}


