package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idStock;
     private Product product;
     private Double buyPrice;
     private Double selPrice;
     private Double qty;
     private Date addedDate;
     private Set wishLists = new HashSet(0);

    public Stock() {
    }

	
    public Stock(Product product) {
        this.product = product;
    }
    public Stock(Product product, Double buyPrice, Double selPrice, Double qty, Date addedDate, Set wishLists) {
       this.product = product;
       this.buyPrice = buyPrice;
       this.selPrice = selPrice;
       this.qty = qty;
       this.addedDate = addedDate;
       this.wishLists = wishLists;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getBuyPrice() {
        return this.buyPrice;
    }
    
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }
    public Double getSelPrice() {
        return this.selPrice;
    }
    
    public void setSelPrice(Double selPrice) {
        this.selPrice = selPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }




}


