package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1



/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer idUserLogin;
     private User user;
     private String userName;
     private String passWord;

    public UserLogin() {
    }

	
    public UserLogin(User user) {
        this.user = user;
    }
    public UserLogin(User user, String userName, String passWord) {
       this.user = user;
       this.userName = userName;
       this.passWord = passWord;
    }
   
    public Integer getIdUserLogin() {
        return this.idUserLogin;
    }
    
    public void setIdUserLogin(Integer idUserLogin) {
        this.idUserLogin = idUserLogin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }




}


