package pojos;
// Generated Apr 20, 2018 2:27:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private UserType userType;
     private String name;
     private String phoneNo;
     private String email;
     private String userName;
     private Set cardDetailses = new HashSet(0);
     private Set userLogins = new HashSet(0);
     private Set shippingAddresses = new HashSet(0);
     private Set wishLists = new HashSet(0);
     private Set checkouts = new HashSet(0);

    public User() {
    }

	
    public User(UserType userType) {
        this.userType = userType;
    }
    public User(UserType userType, String name, String phoneNo, String email, String userName, Set cardDetailses, Set userLogins, Set shippingAddresses, Set wishLists, Set checkouts) {
       this.userType = userType;
       this.name = name;
       this.phoneNo = phoneNo;
       this.email = email;
       this.userName = userName;
       this.cardDetailses = cardDetailses;
       this.userLogins = userLogins;
       this.shippingAddresses = shippingAddresses;
       this.wishLists = wishLists;
       this.checkouts = checkouts;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Set getCardDetailses() {
        return this.cardDetailses;
    }
    
    public void setCardDetailses(Set cardDetailses) {
        this.cardDetailses = cardDetailses;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }
    public Set getShippingAddresses() {
        return this.shippingAddresses;
    }
    
    public void setShippingAddresses(Set shippingAddresses) {
        this.shippingAddresses = shippingAddresses;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }




}


